name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build SDist
        run: python3 setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  python_test:
    name: Test SDist
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Install SDist
        run: |
          pip install dist/*.tar.gz
          rm -rf dist
      - name: Test installed SDist
        run: pytest test/*.py

  cpp_test:
    name: Test Cpp code
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build C++ package
        run: |
          cmake -DBUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug .
          make
      - name: Run test for C++ part
        run: |
          ./bin/test

  upload:
    name: Upload to PyPI
    needs: [build, python_test, cpp_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
